#!/bin/bash

unset SmaBlue_t0
unset SmaBlue_t1
unset SmaBlue_t2
unset SmaBlue_t3
unset SmaBlue_t4
unset SmaOrange_t0
unset SmaOrange_t2
unset SmaOrange_t3
unset SmaOrange_t4
unset SmaOrange_t5
unset SmaRed_t0
unset SmaRed_t1
unset SmaRed_t2
unset SmaRed_t3
unset SmaRed_t4
unset SmaRed_t5
unset SmaRed2_t0
unset SmaRed2_t1
unset SmaRed2_t2
unset SmaRed2_t3
unset SmaRed2_t4
unset SmaRed2_t5
unset SmaRed1_t1
unset SmaGreenBack
unset SmaGreenBack_t0
unset SmaGreenBack_t1
unset SmaGreenBack_t2
unset SmaGreenBack_t3
unset SmaGreenBack_t4
unset SmaLcarNghawjaBlack
unset SmaGreen
unset SmaGreenTab_t2
unset SmaGreenTab_t3
unset SmaGreenTab_t4
unset SmaGreenTab_t5
unset SmaGreenLight_t0
unset SmaGreenLight_t1
unset SmaGreenLight_t2
unset SmaGreenLight_t3
unset SmaGreenLight_t4
unset SmaGreenLight_t5
unset SmaAwragh_t0
unset SmaAwragh_t1
unset SmaAwragh_t2
unset SmaAwragh_t3
unset SmaAwragh_t4
unset Error
unset Warning
unset Success
unset Info
unset Info_t0
unset Info_t1
unset Info_t2
unset Info_t3
unset Info_t4
unset Winw_t4
unset K8sError
unset K8sWarning
unset K8sSuccess
unset K8sInfo
unset center_green
unset center_red
unset center_green_light
unset center_red
